mariadb_env: ENC[AES256_GCM,data:0BYeWkkBIjMn4Wi/ij1RkgRFCrbTfYCiQ5YUPtdGEkqEV5UnXEOZGnBIK7/0vPkVOmd5OYFwnEJ1MV15dpudkQxVcjXIr0RaZjLDnch2x4zPtTbNLUKg+c/AWlvB,iv:t4ThEQH4x3dV5AE7Sl0el/Q9mAC1ouBNj1otitrHJDs=,tag:yTY9FJiOhCLwXIgZ3BFYAw==,type:str]
domserver_env: ENC[AES256_GCM,data:ivMG18LgvR5OtDRrlFtlTHfVtJRW57/EZtTdiGgv8F/BKDHF4wnbg2VnBx4FuFPXc+Ssu+7TCgZtT73C1m5TEjAp9ekclYz4yv6uV1wNCtugeabSZI/w4l0lpf0+yuiLmcH3+GgqZfoYS6rlHKXfhRAF,iv:j2oI18N/uHXjMQg0dnf+R77XesOIunt5xpijPRVcqaI=,tag:LqaFLhD7srGp0/+ITbb6bA==,type:str]
pdns_api_key: ENC[AES256_GCM,data:zMQhf6vDQAM=,iv:3IXiqbSgqueA5kX8yFM/0YKcB6l0uLm/5w+ucTTiNmU=,tag:WoVPxGBkSY/2JKORWRdrgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBenB0L08wZVJMWGNXY3lx
            MXBPQlVaZUFQSWgzTk1wTzV5NUlyajlHNkVrCnZ6U3dDWmNPbERBS0Y3MkR5STMx
            YzRWSnU2ZlNRb01MdmFqV0lLODltZmMKLS0tIGxsOTEvU1YvNkZicG5GdHhLM04y
            NjhiUktkeWF5S2M5KzhTMnFuNFFxQkEK0FGMr9SdnJI0lU8Hk+olSmhujn0UqD+A
            qkm9EoXPeMcHd8S5prmSJ6cAeiyUSpU8yAnWKhq1rnHBlsYT3bBM6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age138avexeemmtm3a2d0njjw23u2s8qrugce590gvcd6klqh4a79qzq96v9dn
    lastmodified: "2026-09-17T18:23:18Z"
    mac: ENC[AES256_GCM,data:kLAtk0YgRL+zkVMS6+IigeEF8tz8BfluUwGja9zsSrFtXEyVgzgRCtf/UNuJwEDEvxizQJ9Z6Ci6CDMyxpfB8lGrSouRBrVl859I4lFKb2mpLZKVPrJ8u89m4eG+NNqusqnb8LGOqXz8SsjS7U1Yonhxd5jiEU4TkEGTX+aWCfc=,iv:3cZ38S3Yw5zO5DMLcqGi5WcvgopGaMiIK68D6oqEYKg=,tag:Tz/+SR6gY3JTgBp01s65wA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
